[project]
name = "claim-search"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["lancedb", "pydantic>2"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
